name: check-release

# WARNING: Actions in this file can access repository secrets. They should never
# execute code of the pull request. All scripts should be fetched from merged
# TokTok code.
on: [workflow_call]

jobs:
  check-release:
    runs-on: ubuntu-slim

    steps:
      - name: Install python dependencies
        run: sudo apt-get update && sudo apt-get install python3-requests
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Checkout TokTok/ci-tools
        uses: actions/checkout@v4
        with:
          repository: TokTok/ci-tools
          path: ci-tools

      - name: Check version against GitHub releases
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_MILESTONE: ${{ github.event.pull_request.milestone.title }}
        run: $GITHUB_WORKSPACE/ci-tools/bin/check_release
